# pyproject.toml

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hdim_opt"
version = "1.6.2" # match version in __init__.py
description = "Numerical optimization, sampling, and analysis toolkit for high-dimensional problems."
readme = {file = "README.md", content-type = "text/markdown"}

authors = [
  {name="Julian Soltes", email="jsoltes@regis.edu"}
]

license = { text = "MIT" }
requires-python = ">=3.8"
keywords = [
    # core
    "high-dimensional",
    "optimization",
    "sampling",
    
    # specific features
    "evolutionary-algorithm",
    "quasi-monte-carlo",
    "sensitivity-analysis",
    "landscape-estimation",
    "symbolic-regression",
    "lorentzian-KDE",
    "stepAIC",
    "waveform-analysis",

    # original methods
    "QUASAR-optimization",
    "hyperellipsoid-sampling"
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: Bio-Informatics"
]
dependencies = ["numpy", "scipy"]

[project.optional-dependencies]
hds = [
    # required by HDS `pip install hdim_opt[hds]`
    "scikit-learn"
]

sensitivity = [
    # required by sensitivity `pip install hdim_opt[sensitivity]`
    "pandas",
    "SALib",
    "gplearn",
    "numba",
    "statsmodels"
]


[project.urls]
Homepage = "https://github.com/jgsoltes/hdim-opt"
Repository = "https://github.com/jgsoltes/hdim-opt"
Issues = "https://github.com/jgsoltes/hdim-opt/issues"
Changelog = "https://github.com/jgsoltes/hdim-opt/releases"
Documentation = "https://github.com/jgsoltes/hdim-opt/blob/main/README.md"

[tool.setuptools.packages.find]
where = ["."]
include = ["hdim_opt*"] # find hdim_opt package